### ISSUE TITLE
El extraño caso del texto palpitante

### ISSUE THREAD

**Issue by dcabo** [civio/medicamentalia-theme#59]
A Javi, en Safari -y tal vez Chrome- en un Macbook con pantalla no Retina, el texto en la página de metodología le cambia de grosor cada pocos segundos, cuando se anima el carrusel de fotos. Esto parece tener que ver con el aliasing en Safari, parece que [no es el único](http://stackoverflow.com/questions/21278020/font-weight-turns-lighter-on-mac-safari).

**Comment by rauldiazpoblete** [comment]
El problema es del sistema de renderizado del texto de Safari. He probado distintas opciones, pero cualquiera de ellas empeora sustancialmente la legibilidad del texto en Chrome (al ser ordenes de -webkit afectan a ambos navegadores a la vez) a costa de mejorar sólo un poco en Safari. Así que teniendo en cuenta que el uso de Chrome es casi 5 veces el de Safari, mejor lo dejamos como está.

**Comment by dcabo** [comment]
:+1:
