### ISSUE TITLE
La infografía principal muestra un error por consola en Safari

### ISSUE THREAD

**Issue by dcabo** [civio/medicamentalia-theme#62]
Todo parece funcionar correctamente, pero aparece un `TypeError: undefined is not an object (evaluating 'b.attr')` en la consola. Y rascando un poco hay un fallo que sí es visible para el usuario: seleccionamos una droga, aparecen las líneas verticales, y reordenamos entonces los países. Veremos entonces que las bolas se mueven pero las líneas se quedan fijas.

**Comment by rauldiazpoblete** [comment]
Sí, es un error al hacer resize debido a la modificación en cómo pintamos las líneas verticales que ya he solucionado aquí: https://github.com/civio/medicamentalia-theme/commit/411d2afd07db70fd1bcb001e717270ad4f439782
